#!/bin/sh
set -e # Exit on error

# Build Type Definition Files
echo "Building Type Definitions..."
npx tsc

# Build Minified Js File
echo "Building Minified JS..."
npm run build

# Compile JSDoc comments into markdown
echo "Generating Documentation..."
npx jsdoc-to-markdown vanillaUtils.js > 'doc/jsdoc.autogenerated.md'

# Combine header doc and the autogenerated doc into README.md
cat doc/header.md doc/jsdoc.autogenerated.md > README.md

# Add the generated files to commit
git update-index --add typings/* vanillaUtils.min.js doc/* README.md

echo "Pre-commit hook completed successfully."